// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SeaMI.Data;

#nullable disable

namespace SeaMI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531162029_primeiramigracao")]
    partial class primeiramigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeaMI.Models.Login", b =>
                {
                    b.Property<int>("cdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdLogin"));

                    b.Property<string>("dsEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("dsSenha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("fgAtivo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("cdLogin");

                    b.ToTable("T_GS_LOGIN");
                });

            modelBuilder.Entity("SeaMI.Models.Usuario", b =>
                {
                    b.Property<int>("cdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdUsuario"));

                    b.Property<int>("cdLogin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("dsNacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("dtNascimento")
                        .HasColumnType("DATE");

                    b.Property<string>("nmUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("nrDocumento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("nrTelefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.HasKey("cdUsuario");

                    b.HasIndex("cdLogin");

                    b.ToTable("T_GS_USUARIO");
                });

            modelBuilder.Entity("SeaMI.Models.Usuario", b =>
                {
                    b.HasOne("SeaMI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("cdLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
