// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SeaMI.Data;

#nullable disable

namespace SeaMI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeaMI.Models.AmostraAgua", b =>
                {
                    b.Property<int>("cdAmostra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdAmostra"));

                    b.Property<string>("dsConcentracaoPlastico")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("dsNutrientes")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("dsOxigenioDissolvido")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("dsPH")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("dsPoluentesQuimicos")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("dsTemperatura")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("dsTurbidez")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<DateTime>("dtColeta")
                        .HasColumnType("DATE");

                    b.HasKey("cdAmostra");

                    b.ToTable("T_GS_AMOSTRA_AGUA");
                });

            modelBuilder.Entity("SeaMI.Models.AmostraUsuario", b =>
                {
                    b.Property<int>("cdAmostraUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdAmostraUser"));

                    b.Property<int>("cdAmostra")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("cdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsAmostra")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<DateTime>("dtAmostra")
                        .HasColumnType("DATE");

                    b.HasKey("cdAmostraUser");

                    b.HasIndex("cdAmostra");

                    b.HasIndex("cdUsuario");

                    b.ToTable("T_GS_AMOSTRA_USUARIO");
                });

            modelBuilder.Entity("SeaMI.Models.AprovacaoRelatorio", b =>
                {
                    b.Property<int>("cdAprovacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdAprovacao"));

                    b.Property<int>("cdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsComentario")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<DateTime>("dtAprovacao")
                        .HasColumnType("DATE");

                    b.Property<int>("fgAprovado")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("cdAprovacao");

                    b.HasIndex("cdUsuario");

                    b.ToTable("T_GS_APROVACAO_RELATORIO");
                });

            modelBuilder.Entity("SeaMI.Models.Login", b =>
                {
                    b.Property<int>("cdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdLogin"));

                    b.Property<string>("dsEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("dsSenha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("fgAtivo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("cdLogin");

                    b.ToTable("T_GS_LOGIN");
                });

            modelBuilder.Entity("SeaMI.Models.MonitoramentoAgua", b =>
                {
                    b.Property<int>("cdMonitoramentoAgua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdMonitoramentoAgua"));

                    b.Property<int>("cdAmostra")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("cdSensor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsMonitoramento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("cdMonitoramentoAgua");

                    b.HasIndex("cdAmostra");

                    b.HasIndex("cdSensor");

                    b.ToTable("T_GS_MONITORAMENTO_AGUA");
                });

            modelBuilder.Entity("SeaMI.Models.RelatorioAgua", b =>
                {
                    b.Property<int>("cdRelatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdRelatorio"));

                    b.Property<int>("cdAprovacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("cdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsRelatorio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("dtRelatorio")
                        .HasColumnType("DATE");

                    b.HasKey("cdRelatorio");

                    b.HasIndex("cdAprovacao");

                    b.HasIndex("cdUsuario");

                    b.ToTable("T_GS_RELATORIO_AGUA");
                });

            modelBuilder.Entity("SeaMI.Models.Sensores", b =>
                {
                    b.Property<int>("cdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdSensor"));

                    b.Property<int>("cdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsSensor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<DateTime>("dtImplementacao")
                        .HasColumnType("DATE");

                    b.Property<string>("nmTecnologia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("cdSensor");

                    b.HasIndex("cdUsuario");

                    b.ToTable("T_GS_SENSORES");
                });

            modelBuilder.Entity("SeaMI.Models.Usuario", b =>
                {
                    b.Property<int>("cdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdUsuario"));

                    b.Property<int>("cdLogin")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("dsArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("dsNacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("dtNascimento")
                        .HasColumnType("DATE");

                    b.Property<string>("nmUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("nrDocumento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("nrTelefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.HasKey("cdUsuario");

                    b.HasIndex("cdLogin");

                    b.ToTable("T_GS_USUARIO");
                });

            modelBuilder.Entity("SeaMI.Models.AmostraUsuario", b =>
                {
                    b.HasOne("SeaMI.Models.AmostraAgua", "AmostraAgua")
                        .WithMany()
                        .HasForeignKey("cdAmostra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaMI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("cdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmostraAgua");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SeaMI.Models.AprovacaoRelatorio", b =>
                {
                    b.HasOne("SeaMI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("cdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SeaMI.Models.MonitoramentoAgua", b =>
                {
                    b.HasOne("SeaMI.Models.AmostraAgua", "AmostraAgua")
                        .WithMany()
                        .HasForeignKey("cdAmostra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaMI.Models.Sensores", "Sensores")
                        .WithMany()
                        .HasForeignKey("cdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmostraAgua");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("SeaMI.Models.RelatorioAgua", b =>
                {
                    b.HasOne("SeaMI.Models.AprovacaoRelatorio", "AprovacaoRelatorio")
                        .WithMany()
                        .HasForeignKey("cdAprovacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaMI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("cdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprovacaoRelatorio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SeaMI.Models.Sensores", b =>
                {
                    b.HasOne("SeaMI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("cdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SeaMI.Models.Usuario", b =>
                {
                    b.HasOne("SeaMI.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("cdLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
